clase_33/vinoteca/app_vino/urls.py
from django.urls import path 
from .router import router 

from .views import      VinosListView   \
                    ,   VinosDetailView \
                    ,   VinosCreateView \
                    ,   VinosUpdateView \
                    ,   VinosDeleteView

app_name = "vinos"

urlpatterns = [
    path("", VinosListView.as_view(), name="all"),
    path("create/", VinosCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", VinosDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", VinosUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", VinosDeleteView.as_view(), name="delete")
    
]

urlpatterns += router.urls

clase_33/vinoteca/vinoteca/urls.py
from django.contrib import admin
from django.urls import path , include

from .views import Vinoteca

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", Vinoteca.as_view(), name="vinoteca"),
    path("vinos/", include("app_vino.urls")),
]

clase_33/vinoteca/app_vino/models.py
from django.db import models

# Create your models here.

class Vino(models.Model):
    nombre  =  models.CharField(max_length=200)
    rating = models.PositiveSmallIntegerField(blank=False,null=False)
    abv = models.FloatField(blank=True, null=True)


    class Meta:
        db_table = "vino_table"

    def __str__(self):
        return f"El vino: {self.nombre}, Rating {self.abv}"
    
    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]
        
        

clase_33/vinoteca/app_vino/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View

from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.views.generic.detail import DetailView


from .models import Vino

# Create your views here.


class VinosBaseView(View):
    template_name = 'vinos.html'
    model = Vino
    fields = '__all__'
    success_url = reverse_lazy('vinos:all')
    

class VinosListView(VinosBaseView,ListView):
    """
    ESTO ME PERMITE CREAR UNA VISTA CON LOS VINOS
    """
    
class VinosDetailView(VinosBaseView,DetailView):
    template_name = "vino_detail.html"
    
class VinosCreateView(VinosBaseView,CreateView):
    template_name = "vino_create.html"
    extra_context = {
        "tipo": "Crear vino"
    }
    
    
class VinosUpdateView(VinosBaseView,UpdateView):
    template_name = "vino_create.html"
    extra_context = {
        "tipo": "Actualizar vino"
    }
    
class VinosDeleteView(VinosBaseView,DeleteView):
    template_name = "vino_delete.html"
    extra_context = {
        "tipo": "Borrar vino"
    }
    

clase_33/vinoteca/vinoteca/views.py
from django.views.generic import TemplateView

class Vinoteca(TemplateView):
    template_name = "index.html"
    

clase_33/vinoteca/app_vino/templates/vino_create.html
{% extends 'base_vinoteca.html' %}
{% block content %}

<main>
    <div class="main-color-vinos">
        <h1>CREAR VINO</h1>
        <form method="post">
            {% csrf_token %}
            <div>{{form.as_p}}</div>
            <input type="submit" value="{{ tipo }}" />
        </form>

        <a href="{% url 'vinos:all' %}">Volvamos al Inicio</a>
    </div>
</main>
{% endblock %}

clase_33/vinoteca/app_vino/templates/vino_delete.html
{% extends 'base_vinoteca.html' %} {% block content %}

<main>
    <div class="main-color-vinos">
        <h1>Estas seguro ue deseas borrar este vino?</h1>
        <h2>{{vino.nombre}}</h2>
        <form method="post">
            {% csrf_token %}
            <div>{{form.as_p}}</div>
            <input type="submit" value="{{ tipo }}" />
        </form>

        <a href="{% url 'vinos:all' %}">Cancelar</a>
    </div>
</main>
{% endblock %}

clase_33/vinoteca/app_vino/templates/vino_detail.html
{% extends 'base_vinoteca.html' %}
{% block content %}

<main>
    <div class="main-color-vinos">
        <h1>{{vino.nombre}}</h1>
        {% for label, value in vino.get_fields %}

        <p>{{label | upper}}</p>
        <p>{{value}}</p>

        {% endfor %}

        <a href="{% url 'vinos:all' %}">BACK</a>
    </div>
</main>
{% endblock %}

clase_33/vinoteca/app_vino/templates/vinos.html
{% extends 'base_vinoteca.html' %}

{% block content %}

<main>
    <div class="main-color-vinos">
        <h1>Todos los vinos</h1>
        <h2><a href="{% url 'vinos:create' %}">CREAR VINO</a></h2>
        {% for vino in vino_list%}
        <div class="list">
            <span>
                <p>{{forloop.counter}}</p>
            </span>
            <span>
                <p>{{vino.nombre}}</p>
            </span>
            <span>
                <label for="">Detalle: </label>
                <a href="{% url 'vinos:detail' vino.id %}">+</a>
            </span>
            <span>
                <label for="">Editar: </label>
                <a href="{% url 'vinos:update' vino.id %}">+</a>
            </span>
            <span>
                <label for="">Borrar: </label>
                <a href="{% url 'vinos:delete' vino.id %}">+</a>
            </span>
        </div>

        {% endfor %}
    </div>
</main>
{% endblock %}

clase_33/vinoteca/templates/base_vinoteca.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static './css/main.css' %}" />
    <title>Document</title>
</head>

<body>
    <div id="app">
        <header id="header">
            <ul>
                <li v-for="item in lista" @click="clickedShow">
                    <a v-bind:href="`#${item.toLowerCase()}`">-- item --</a>
                </li>
                <li>
                    <a href="{% url 'vinos:all' %}">VINOS</a>
                </li>
            </ul>
        </header>

        {% block content %}
        {% endblock %}

    </div>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://unpkg.com/vue@next"></script>
    <script src="{% static './js/vueScript.js' %}"></script>
</body>

</html>

clase_33/vinoteca/templates/index.html
{% extends 'base_vinoteca.html' %}
{% load static %}
{% block content %}

<main>
    <div class="up">
        <a href="#header">🔼</a>
    </div>

    <section class="primer_sector" id="inicio" v-show="value == 'INICIO'">
        <div class="data">
            <h1>QUIEN SOY?</h1>
            <p>-- intro --</p>
        </div>
        <div class="img">
            <img src="{% static  './imgs/linux.png' %}" alt="linux" class="linux_images" class="img" />
        </div>
    </section>
    <section class="segundo_sector" id="contacto" v-show="value == 'CONTACTO'">
        <div class="bg"></div>
        <div class="data">
            <h1>Por email</h1>
            <h4>anderson.ocana@bue.edu.ar</h4>
            <h2>GITHUB</h2>
            <h4>https://github.com/andru-oca</h4>
        </div>
    </section>

    <section class="tercer_sector" id="habilidades" v-show="value == 'HABILIDADES'">
        <div class="data">
            <h1 v-for="habilidad in habilidades">
                -- habilidad --
            </h1>
        </div>
        <div class="bg2"></div>
    </section>
    <sector-component :value="value"></sector-component>
</main>

{% endblock %}